name: stevenroose
version: 0.1.1+2
description: A collection of useful Dart code snippets.
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-snippets
dependencies:
  cryptoutils: ">=0.1.9"
  http: ">=0.11.1+1 <1.0.0"
  json_rpc_2: ">=1.0.0 <2.0.0"
  zengen: ">=0.3.1 <0.4.0"

dev_dependencies:
  browser: any
  source_gen: any
